name: Generate RSS Feed

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  generate-rss:
    runs-on: ubuntu-latest  # Using Ubuntu as the base runner for .NET

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Use the version of .NET your project is targeting

      # Step 3: Restore the project dependencies
      - name: Restore dependencies
        run: dotnet restore website-rss-feed.sln  # Adjust with your solution file path

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build website-rss-feed.sln --configuration Release

      # Step 5: Run the GenerateRSS.cs program
      - name: Run RSS Generation
        run: dotnet run --project website-rss-feed.csproj

      # Debugging: List files in the build folder (for debugging)
      - name: List files
        run: |
          ls -R

      # Step 6: Move generated file to a trackable folder
      - name: Move generated file to trackable folder
        run: |
          mv ./bin/Release/net8.0/rss.xml .rss.xml  # Adjust paths as needed
          git add ./rss.xml
          git status 

      # Step 7: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Commit and push if changes exist
          if git diff --exit-code ./generated/rss.xml; then
            echo "No changes to commit"
          else
            git commit -m "Update RSS feed"
            git push
          fi